### PR TITLE
feat(project): add deploy command contract

### PR DESCRIPTION
**Pull request by notgitika**
## Summary

- add the `project deploy` handler and `--target` contract
- define deployment target validation and deployment result types
- synchronize the closed AgentCore region enum with the current supported-region list
- wire manager/backend deploy interfaces with an intentionally unimplemented CDK operation

## Stack

This is PR 2 of 4 decomposing #2001. The command remains nonfunctional until the final PR. Review and merge bottom-up.

1. #2055 - backend build boundary
2. **#2056 - deploy command contract (this PR)**
3. #2057 - CDK Toolkit adapter
4. #2058 - safe deployment implementation

typecheck, lint, format, test all pass

### CODE REVIEW

File: src/handlers/project/project.test.ts [hunk 1]
```diff
@@ -921,3 +921,15 @@ describe("project build", () => {
     await expect(run(["build"])).rejects.toThrow(/npm install/);
   });
 });
+
+describe("project deploy", () => {
+  test("requires an AgentCore project", async () => {
```
Comment (Hweinstock) [inline src/handlers/project/project.test.ts:618]: likely OOS here, but we should probably have a test that does this for all project commands not just deploy.

File: src/handlers/project/types.ts [hunk 2]
```diff
@@ -28,6 +28,16 @@ export type ProjectEvent = {
   message: string;
 };
 
+export type DeployProjectInput = {
+  /** Name of the aws-targets.json entry to deploy. */
+  target: string;
+};
+
+export type DeployResult = {
+  /** Outputs returned by the deployed stack, keyed by CloudFormation output name. */
```
Comment (Hweinstock) [inline src/handlers/project/types.ts]: for non-IAC / terraform backends, what would this represent? I don't think we need to know exactly, but want to make sure this api is not coupling us to CDK.

File: src/handlers/project/deploy/index.test.ts [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+} from "../types";
+import { createDeployProjectHandler } from ".";
+
+const project: Project = {
+  name: "orders",
+  rootPath: "/workspace/orders",
+  spec: ProjectSpecSchema.parse({ name: "orders", version: 1 }),
+};
+
+function fakeProjectManager(result: DeployResult, events: ProjectEvent[] = []) {
```
Comment (Hweinstock) [inline src/handlers/project/deploy/index.test.ts]: is it possible to re-use https://github.com/aws/agentcore-cli/blob/33e2d2f8c5e698fb19d270c033fa013161477a78/src/testing/TestCoreClient.tsx#L1951-L1960 like how https://github.com/aws/agentcore-cli/blob/33e2d2f8c5e698fb19d270c033fa013161477a78/src/handlers/project/project.test.ts#L88 does it?

**Review by Hweinstock — COMMENTED** [review]
small questions, but approach lgtm. I can take another look once the dependent changes are merged.

File: src/handlers/project/project.test.ts (hunk 1 above)
Comment (notgitika) [reply src/handlers/project/project.test.ts:618]: yes! I will add it to all as a follow up :)

File: src/handlers/project/types.ts (hunk 2 above)
Comment (notgitika) [reply src/handlers/project/types.ts]: yeah let me change the comment. 

The type is neutral for those backends so the comment is wrong at this point. It's just a string map so any backend can fill it, CDK from CFN outputs, Terraform from terraform output etc. nothing reads specific keys out of it, we just print them or dump them with --json. I'll reword the doc so it stops saying cfn

File: src/handlers/project/deploy/index.test.ts (hunk 3 above)
Comment (notgitika) [reply src/handlers/project/deploy/index.test.ts]: ah yes I should have done this. let me switch it

File: src/projectSchemas/aws-targets.ts [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+  "us-west-2",
+  "us-gov-west-1",
+]);
+
+export const DeploymentTargetNameSchema = z
+  .string()
+  .min(1)
+  .max(64)
+  .regex(
+    /^[a-zA-Z][a-zA-Z0-9_-]*$/,
```
Comment (nborges-aws) [inline src/projectSchemas/aws-targets.ts]: Can we remove underscores from the regex? On main we do not accept underscores: [aws-targets.ts](https://github.com/aws/agentcore-cli/blob/main/src/schema/schemas/aws-targets.ts#L42)

Our CDK normalizes all underscores to hyphens, so this is more of a nit. But for robustness we should disallow upfront.

**Comment by Hweinstock** [comment]
I think there are some merge conflicts: `src/handlers/project/project.test.ts`.

File: src/projectSchemas/aws-targets.ts (hunk 4 above)
Comment (notgitika) [reply src/projectSchemas/aws-targets.ts]: nice catch! just getting it done now

File: src/core/project/manager.tsx [hunk 5]
```diff
@@ -281,6 +286,41 @@ export class FsProjectManager implements ProjectManager {
...
+  ): AsyncGenerator<ProjectEvent, DeployResult> {
+    const targetsPath = join(project.rootPath, "agentcore", "aws-targets.json");
+    if (!existsSync(targetsPath)) {
+      throw new ProjectStateError(
+        `No deployment targets are configured for project '${project.name}'. ` +
+          `Add ${targetsPath}, for example:\n\n${TARGETS_EXAMPLE}`,
+      );
+    }
+
+    const targets = await this.json.read(targetsPath, AwsDeploymentTargetsSchema);
```
Comment (tejaskash) [inline src/core/project/manager.tsx:332]: These validation messages never actually reach the user here. `json.read` wraps any schema failure in `DeserializationError`, whose message is just `Failed to deserialize file at "<path>"` (io/json.ts:55, errors.tsx:98) — the zod detail only goes to the debug log, and the top-level reporter prints `error.message`. So someone who typos a region or duplicates a name in this hand-edited file (which our own error text above tells them to write) just gets an opaque "failed to deserialize" with no idea which field is wrong.

We already do the right thing one method up: `addResource` rethrows `InputValidationError(z.prettifyError(...))` (manager.tsx:190). Worth mirroring that — catch `DeserializationError` here and rethrow with the prettified cause, or fix it once in `FsReadWriteJson.read` so every hand-edited file benefits. Either way we should add a handler-level test for what the user actually sees; the current schema tests pass in isolation and dont catch this.

Comment (Hweinstock) [reply src/core/project/manager.tsx:332]: I think we should fix in the source, such that the error message includes the schema failure information (perhaps extending `DeserializationError` to take an optional detail field that corresponds to the prettified zod error in this case) , but I think that could be a follow-up.

Comment (notgitika) [reply src/core/project/manager.tsx:332]: thanks for the catch, fixed! I also added the tests

**Review by nborges-aws — DISMISSED** [review]
LGTM thanks for fixes!

File: src/io/json.ts [hunk 6]
```diff
@@ -52,7 +52,10 @@ export class FsReadWriteJson implements ReadWriteJson {
           errorMessage: parseResult.error.message,
         })
         .error(`failed to validate parsed json file`);
-      throw new DeserializationError(filePath, { cause: parseResult.error });
+      throw new DeserializationError(filePath, {
+        cause: parseResult.error,
+        details: z.prettifyError(parseResult.error),
```
Comment (Hweinstock) [inline src/io/json.ts:57]: haha I refreshed and you implemented exactly what I was thinking, crazy!

File: src/testing/TestCoreClient.tsx [hunk 7]
```diff
@@ -1179,6 +1180,9 @@ export class TestGatewayClient implements CoreGatewayClient {
 type TestCoreClientOptions = {
   logger?: Logger;
   json?: ReadWriteJson;
+  // Stubs one backend rather than the whole manager, so tests keep the real
```
Comment (Hweinstock) [inline src/testing/TestCoreClient.tsx]: nit: I think this is communicated by the partial and doesn't warrant a comment.

File: src/handlers/project/deploy/index.test.ts [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+    await inProjectWithTargets(subject, []);
+
+    await expect(subject.run()).rejects.toThrow(/No deployment targets are configured/);
+    expect(subject.calls).toEqual([]);
+  });
+});
+
+// aws-targets.json is hand-edited, so these assert on the message the user
+// actually sees rather than on the schema in isolation: the reporter prints only
+// error.message, so a validation detail left in `cause` may as well not exist.
```
Comment (Hweinstock) [inline src/handlers/project/deploy/index.test.ts]: wait didn't we fix this by appending the detail to the message?

File: src/handlers/project/deploy/index.test.ts [hunk 9]
```diff
@@ -0,0 +1,202 @@
...
+    async *deploy(project, input) {
+      calls.push({ project, input });
+      yield* events;
+      return result;
+    },
+  };
+  return { calls, backend };
+}
+
+function harness(result: DeployResult, events: ProjectEvent[] = []) {
```
Comment (Hweinstock) [inline src/handlers/project/deploy/index.test.ts]: what does this have to with `harness` or is this like a testing harness (unrelated to AgentCore harness)? If so, maybe we can rename to avoid confusion.

File: src/handlers/project/deploy/index.test.ts [hunk 10]
```diff
@@ -0,0 +1,202 @@
...
+  const directory = await inTempDirectory();
+  await subject.create(["create", "--name", "orders", "--skip-install", "--skip-git"]);
+  const projectRoot = join(directory, "orders");
+  await writeFile(join(projectRoot, "agentcore", "aws-targets.json"), contents);
+  process.chdir(projectRoot);
+  return projectRoot;
+}
+
+/** Scaffolds a project with deployment targets and cds into it. */
+function inProjectWithTargets(
```
Comment (Hweinstock) [inline src/handlers/project/deploy/index.test.ts]: nit: this feels like unnecessary indirection.

File: src/handlers/project/deploy/index.ts [hunk 11]
```diff
@@ -1,11 +1,53 @@
...
+import { JsonKey } from "../../keys";
+import type { DeployResult, ProjectManager } from "../types";
 
-export const createDeployProjectHandler = () =>
+type DeployProjectHandlerConfig = {
+  projectManager: ProjectManager;
+  io: AppIO;
+};
+
+async function runDeploy(
```
Comment (Hweinstock) [inline src/handlers/project/deploy/index.ts]: nit: is there a reason these should live in a separate functions, rather than in-lined? Do we expect them to be re-used?

**Review by Hweinstock — COMMENTED** [review]
few comments on testing and some nits, but I like the direction!

File: src/io/json.ts (hunk 6 above)
Comment (notgitika) [reply src/io/json.ts:57]: 🧙🏼

File: src/testing/TestCoreClient.tsx (hunk 7 above)
Comment (notgitika) [reply src/testing/TestCoreClient.tsx]: removed

File: src/handlers/project/deploy/index.test.ts (hunk 8 above)
Comment (notgitika) [reply src/handlers/project/deploy/index.test.ts]: stale comment block i didnt catch this, removed

File: src/handlers/project/deploy/index.test.ts (hunk 9 above)
Comment (notgitika) [reply src/handlers/project/deploy/index.test.ts]: it was a testing harness I renamed it to testDeployCommand

File: src/handlers/project/deploy/index.test.ts (hunk 10 above)
Comment (notgitika) [reply src/handlers/project/deploy/index.test.ts]: collapsed to one helper taking file contents. now, callers pass JSON.stringify(...), so the malformed-JSON case is just another call.

File: src/handlers/project/deploy/index.ts (hunk 11 above)
Comment (notgitika) [reply src/handlers/project/deploy/index.ts]: no resuse planned so I just made them to be inline functions

**Review by tejaskash — APPROVED** [review]
All actionable review comments are addressed. I verified the final head against current refactor and reran the full local test, typecheck, lint, and formatting checks.

**Review by nborges-aws — APPROVED** [review]
